/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Empresa;

import Controle.ControlePrincipal;
import DAO.GeneralDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class AtualizarEmpresa extends javax.swing.JDialog {

    private GeneralDAO dao;
    private String nomeAntigo, areaAntigo, segmentoAntigo;
    private String nome, area, segmento;
    private ControlePrincipal controlePrincipal = new ControlePrincipal();

    /**
     * Creates new form AtualizarEmpresa
     */
    public AtualizarEmpresa(java.awt.Frame parent, boolean modal,
            GeneralDAO dao, String nomeAntigo, String areaAntigo, String segmentoAntigo) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        this.nomeAntigo = nomeAntigo;
        this.areaAntigo = areaAntigo;
        this.segmentoAntigo = segmentoAntigo;
        jTextFieldNomeAntigo.setText("Nome Fantasia: " + nomeAntigo);
        jTextFieldAreaAntigo.setText("Área: " + areaAntigo);
        jTextFieldSegmentoAntigo.setText("Segmento Mercado: " + segmentoAntigo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeAntigo = new javax.swing.JTextField();
        jTextFieldAreaAntigo = new javax.swing.JTextField();
        jTextFieldSegmentoAntigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxArea = new javax.swing.JComboBox();
        jComboBoxSegmento = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dados Antigos");

        jTextFieldNomeAntigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNomeAntigo.setText("jTextField1");
        jTextFieldNomeAntigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNomeAntigo.setEnabled(false);

        jTextFieldAreaAntigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldAreaAntigo.setText("jTextField1");
        jTextFieldAreaAntigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAreaAntigo.setEnabled(false);

        jTextFieldSegmentoAntigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSegmentoAntigo.setText("jTextField1");
        jTextFieldSegmentoAntigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSegmentoAntigo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome Fantasia");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dados Novos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Área");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Segmento Mercado");

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBoxArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Água - Energia - Gás", "Alimentos", "Demais Produtos", "Demais Serviços", "Educação", "Habitação", "Produtos de Telefonia e Informática", "Produtos Eletrodomésticos e Eletrônicos", "Saúde", "Serviços Financeiros", "Telecomunicações", "Transportes", "Turismo/Viagens" }));
        jComboBoxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAreaActionPerformed(evt);
            }
        });

        jComboBoxSegmento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSegmento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administradoras de Consórcios", "Agências de Viagens", "Artigos Esportivos", "Bancos de Dados e Cadastros de Consumidores", "Bancos - Financeiras e Administradoras de Cartão", "Comércio Eletrônico", "Corretoras e Sociedades de Seguros - Capitalização e Previdência", "Editoras", "Empresas de Pagamento Eletrônico", "Empresas de Recuperação de Crédito", "Energia Elétrica - Gás - Água e Esgoto", "Estabelecimentos de Ensino", "Fabricantes - Eletroeletrônicos - Produtos de Telefonia e Informática", "Fabricantes - Eletroportáteis e Artigos de Uso Doméstico e Pessoal", "Fabricantes - Linha Branca", "Farmácias", "Material de Construção e Acabamento", "Montadoras - Concessionárias e Prestadores de Serviços Automotivos", "Móveis e Artigos de Decoração", "Operadoras de Planos de Saúde e Administradoras de Benefícios", "Operadoras de Telecomunicações (Telefonia - Internet - TV por assinatura)", "Peças e Serviços Automotivos", "Perfumaria - Cosméticos e Higiene Pessoal", "Programas de Fidelidade", "Provedores de Conteúdo e Outros Serviços na Internet", "Serviços e Produtos Automotivos", "Supermercados", "Transporte Aéreo", "Transporte Terrestre", "Varejo", "Vestuário - Calçados e Têxteis" }));
        jComboBoxSegmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSegmentoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Atualizar Empresa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSegmentoAntigo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addComponent(jTextFieldAreaAntigo, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNomeAntigo, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome)
                            .addComponent(jComboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSegmento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(337, 337, 337))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNomeAntigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAreaAntigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSegmentoAntigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAreaActionPerformed
        area = jComboBoxArea.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxAreaActionPerformed

    private void jComboBoxSegmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSegmentoActionPerformed
        segmento = jComboBoxSegmento.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxSegmentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nome = jTextFieldNome.getText();

        if (nome.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome para a empresa!");
        } else if (nome.length() > 100) {
            JOptionPane.showMessageDialog(null, "Nome da empresa deve ter menos de 100 caracteres!");
        } else {
            if (segmento == null) {
                segmento = "Administradoras de Consórcios";
            }

            if (area == null) {
                area = "Água - Energia - Gás";
            }

            if (controlePrincipal.verificanomefantasia(nome, area, segmento, dao)) { // já existe empresa com esse nome
                JOptionPane.showMessageDialog(null, "Empresa " + nome + " já cadastrada no banco!", "Erro!", JOptionPane.ERROR_MESSAGE);
                nome = "";
            } else {
                String saida = "Deseja atualizar a empresa?\n\nNome antigo: " + nomeAntigo
                        + "\nÁrea antiga: " + areaAntigo + "\nSegmento Mercado Antigo: " + segmentoAntigo
                        + "\n\nNome novo: " + nome
                        + "\nÁrea nova: " + area + "\nSegmento Mercado novo: " + segmento;

                int resposta = JOptionPane.showConfirmDialog(null, saida);
                if (resposta == 0) {
                    if (controlePrincipal.atualizarEmpresa(nomeAntigo, areaAntigo, segmentoAntigo, nome, area, segmento, dao)) {
                        JOptionPane.showMessageDialog(null, "Empresa " + nome + " atualizada com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro na atualização da empresa " + nome + "!");
                    }

                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxArea;
    private javax.swing.JComboBox jComboBoxSegmento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldAreaAntigo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeAntigo;
    private javax.swing.JTextField jTextFieldSegmentoAntigo;
    // End of variables declaration//GEN-END:variables
}
