/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Empresa;

import Controle.ControlePrincipal;
import Modelo.ModeloTabela;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import DAO.GeneralDAO;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;

/**
 *
 * @author Gustavo
 */
public class BuscarEmpresa extends javax.swing.JDialog {

    private GeneralDAO dao;
    private ControlePrincipal controlePrincipal = new ControlePrincipal();
    private List<String> empresas;
    private String nome;
    private Frame parent;

    /**
     * Creates new form BuscarEmpresa
     */
    public BuscarEmpresa(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        preencherComboBox();
        jTableEmpresasBuscadas.setAutoCreateRowSorter(true);
        Toolkit kit = this.getToolkit();
        Image icone = kit.getImage("src/Icones/empresa.png");
        this.setIconImage(icone);
        this.parent = parent;
    }

    private void preencherComboBox() {
        empresas = dao.buscaAtributo("select distinct(nomefantasia) from Empresa order by nomefantasia");
        for (String s : empresas) {
            jComboBoxEmp.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxEmp = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresasBuscadas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Empresa");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        jComboBoxEmp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableEmpresasBuscadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableEmpresasBuscadas);

        jButton1.setText("Atualizar Empresa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deletar Empresa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEmp, 0, 323, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(58, 58, 58))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(248, 248, 248)
                            .addComponent(jButtonBuscar)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jButtonBuscar)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpActionPerformed
        nome = jComboBoxEmp.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxEmpActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        if (nome == null) {
            nome = empresas.get(0);
        }
        ArrayList emp = controlePrincipal.buscarEmpresa(nome, dao);
        jTableEmpresasBuscadas.setVisible(true);
        jScrollPane1.setVisible(true);
        preencherTabela(emp, nome);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selecionada = jTableEmpresasBuscadas.getSelectedRow();
        if (selecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma empresa da tabela!", "Selecione uma empresa", JOptionPane.INFORMATION_MESSAGE);
        } else {

            String area = jTableEmpresasBuscadas.getValueAt(selecionada, 1).toString();
            String segmento = jTableEmpresasBuscadas.getValueAt(selecionada, 2).toString();

            String pergunta = "Deseja deletar a empresa?\n\nNome: " + nome + "\nÁrea: " + area + "\nSegmento Mercado: " + segmento;

            int resposta = JOptionPane.showConfirmDialog(null, pergunta, "Deletar Empresa", JOptionPane.WARNING_MESSAGE);

            if (resposta == 0) {
                if (controlePrincipal.deletarEmpresa(nome, area, segmento, dao)) {
                    JOptionPane.showMessageDialog(null, "Empresa " + nome + " deletada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro! Empresa " + nome
                            + " não foi deletada!", "Erro", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selecionada = jTableEmpresasBuscadas.getSelectedRow();
        if (selecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma empresa da tabela!", "Selecione uma empresa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String area = jTableEmpresasBuscadas.getValueAt(selecionada, 1).toString();
            String segmento = jTableEmpresasBuscadas.getValueAt(selecionada, 2).toString();
            AtualizarEmpresa dialog = new AtualizarEmpresa(parent, true, dao, nome, area, segmento);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void preencherTabela(ArrayList empresas, String nome) {
        try {
            String[] nomeColunas = new String[]{"Nome", "Área", "Segmento Mercado"};

            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            ModeloTabela modeloTabela = new ModeloTabela(empresas, nomeColunas);
            jTableEmpresasBuscadas.setModel(modeloTabela);

            jTableEmpresasBuscadas.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableEmpresasBuscadas.getColumnModel().getColumn(0).setResizable(true);
            jTableEmpresasBuscadas.getColumnModel().getColumn(0).setHeaderValue(modeloTabela.getColumnNome(0));
            jTableEmpresasBuscadas.getColumnModel().getColumn(0).setCellRenderer(centralizado);

            jTableEmpresasBuscadas.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableEmpresasBuscadas.getColumnModel().getColumn(1).setResizable(true);
            jTableEmpresasBuscadas.getColumnModel().getColumn(1).setHeaderValue(modeloTabela.getColumnNome(1));
            jTableEmpresasBuscadas.getColumnModel().getColumn(1).setCellRenderer(centralizado);

            jTableEmpresasBuscadas.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableEmpresasBuscadas.getColumnModel().getColumn(2).setResizable(true);
            jTableEmpresasBuscadas.getColumnModel().getColumn(2).setHeaderValue(modeloTabela.getColumnNome(2));
            jTableEmpresasBuscadas.getColumnModel().getColumn(2).setCellRenderer(centralizado);

            jTableEmpresasBuscadas.getTableHeader().setReorderingAllowed(false);
            jTableEmpresasBuscadas.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTableEmpresasBuscadas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "Erro ao listar as empresas de nome " + nome + "!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox jComboBoxEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresasBuscadas;
    // End of variables declaration//GEN-END:variables
}
