/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Empresa;

import Controle.ControlePrincipal;
import javax.swing.JOptionPane;
import DAO.GeneralDAO;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Gustavo
 */
public class InserirEmpresa extends javax.swing.JDialog {

    private String nome, area, segmento;
    private ControlePrincipal controlePrincipal;
    private GeneralDAO dao;

    /**
     * Creates new form CadastrarEmpresa
     */
    public InserirEmpresa(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        controlePrincipal = new ControlePrincipal();
        Toolkit kit = this.getToolkit();
        Image icone = kit.getImage("src/Icones/empresa.png");
        this.setIconImage(icone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeFantasia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxArea = new javax.swing.JComboBox();
        jButtonCadastraEmpresaView = new javax.swing.JButton();
        jComboBoxSegmento = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Empresa");

        jLabelNomeFantasia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeFantasia.setText("Nome Fantasia");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Área");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Segmento Mercado");

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jComboBoxArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Água - Energia - Gás", "Alimentos", "Demais Produtos", "Demais Serviços", "Educação", "Habitação", "Produtos de Telefonia e Informática", "Produtos Eletrodomésticos e Eletrônicos", "Saúde", "Serviços Financeiros", "Telecomunicações", "Transportes", "Turismo/Viagens" }));
        jComboBoxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAreaActionPerformed(evt);
            }
        });

        jButtonCadastraEmpresaView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCadastraEmpresaView.setText("Cadastrar Empresa");
        jButtonCadastraEmpresaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraEmpresaViewActionPerformed(evt);
            }
        });

        jComboBoxSegmento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSegmento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administradoras de Consórcios", "Agências de Viagens", "Artigos Esportivos", "Bancos de Dados e Cadastros de Consumidores", "Bancos - Financeiras e Administradoras de Cartão", "Comércio Eletrônico", "Corretoras e Sociedades de Seguros - Capitalização e Previdência", "Editoras", "Empresas de Pagamento Eletrônico", "Empresas de Recuperação de Crédito", "Energia Elétrica - Gás - Água e Esgoto", "Estabelecimentos de Ensino", "Fabricantes - Eletroeletrônicos - Produtos de Telefonia e Informática", "Fabricantes - Eletroportáteis e Artigos de Uso Doméstico e Pessoal", "Fabricantes - Linha Branca", "Farmácias", "Material de Construção e Acabamento", "Montadoras - Concessionárias e Prestadores de Serviços Automotivos", "Móveis e Artigos de Decoração", "Operadoras de Planos de Saúde e Administradoras de Benefícios", "Operadoras de Telecomunicações (Telefonia - Internet - TV por assinatura)", "Peças e Serviços Automotivos", "Perfumaria - Cosméticos e Higiene Pessoal", "Programas de Fidelidade", "Provedores de Conteúdo e Outros Serviços na Internet", "Serviços e Produtos Automotivos", "Supermercados", "Transporte Aéreo", "Transporte Terrestre", "Varejo", "Vestuário - Calçados e Têxteis" }));
        jComboBoxSegmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSegmentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelNomeFantasia)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jComboBoxSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jButtonCadastraEmpresaView)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxArea, jComboBoxSegmento, jTextFieldNome});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeFantasia))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonCadastraEmpresaView)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxArea, jComboBoxSegmento, jTextFieldNome});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSegmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSegmentoActionPerformed
        segmento = jComboBoxSegmento.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxSegmentoActionPerformed

    private void jComboBoxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAreaActionPerformed
        area = jComboBoxArea.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxAreaActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed

    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonCadastraEmpresaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraEmpresaViewActionPerformed
        nome = jTextFieldNome.getText();

        if (nome.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome para a empresa!");
        } else if (nome.length() > 100) {
            JOptionPane.showMessageDialog(null, "Nome da empresa deve ter menos de 100 caracteres!");
        } else {
            if (segmento == null) {
                segmento = "Administradoras de Consórcios";
            }

            if (area == null) {
                area = "Água - Energia - Gás";
            }

            if (controlePrincipal.verificanomefantasia(nome, area, segmento, dao)) { // já existe empresa com esse nome
                JOptionPane.showMessageDialog(null, "Empresa " + nome + " já cadastrada no banco!", "Erro!", JOptionPane.ERROR_MESSAGE);
                nome = "";
            } else {
                if (controlePrincipal.inserirEmpresa(nome, area, segmento, dao)) {
                    JOptionPane.showMessageDialog(null, "Empresa " + nome + " cadastrada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro no cadastro da empresa " + nome + "!");
                }

            }
        }


    }//GEN-LAST:event_jButtonCadastraEmpresaViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastraEmpresaView;
    private javax.swing.JComboBox jComboBoxArea;
    private javax.swing.JComboBox jComboBoxSegmento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNomeFantasia;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
