/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Empresa;

import Controle.ControlePrincipal;
import Controle.*;
import Mapeamento.Usuario;
import Modelo.ModeloTabela;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import DAO.GeneralDAO;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Gustavo
 */
public class ListarEmpresa extends javax.swing.JDialog {

    private GeneralDAO dao;
    private ControlePrincipal controlePrincipal = new ControlePrincipal();

    /**
     * Creates new form ListarUsuario
     */
    public ListarEmpresa(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        preencherTabela();
        jTableListarEmpresa.setAutoCreateRowSorter(true); 
        Toolkit kit = this.getToolkit();
        Image icone = kit.getImage("src/Icones/empresa.png");
        this.setIconImage(icone);
    }

    public void preencherTabela() {

        try {
            String[] nomeColunas = new String[]{"Nome", "Área", "Segmento Mercado"};
            ArrayList dados = controlePrincipal.listarEmpresas(dao);
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            ModeloTabela modeloTabela = new ModeloTabela(dados, nomeColunas);
            jTableListarEmpresa.setModel(modeloTabela);

            jTableListarEmpresa.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableListarEmpresa.getColumnModel().getColumn(0).setResizable(true);
            jTableListarEmpresa.getColumnModel().getColumn(0).setHeaderValue(modeloTabela.getColumnNome(0));
            jTableListarEmpresa.getColumnModel().getColumn(0).setCellRenderer(centralizado);

            jTableListarEmpresa.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableListarEmpresa.getColumnModel().getColumn(1).setResizable(true);
            jTableListarEmpresa.getColumnModel().getColumn(1).setHeaderValue(modeloTabela.getColumnNome(1));
            jTableListarEmpresa.getColumnModel().getColumn(1).setCellRenderer(centralizado);

            jTableListarEmpresa.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableListarEmpresa.getColumnModel().getColumn(2).setResizable(true);
            jTableListarEmpresa.getColumnModel().getColumn(2).setHeaderValue(modeloTabela.getColumnNome(2));
            jTableListarEmpresa.getColumnModel().getColumn(2).setCellRenderer(centralizado);

            jTableListarEmpresa.getTableHeader().setReorderingAllowed(false);
            jTableListarEmpresa.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTableListarEmpresa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "Erro ao listar as empresas cadastradas!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarEmpresa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas Cadastradas");

        jTableListarEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableListarEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarEmpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListarEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarEmpresaMouseClicked
        int selecionada = jTableListarEmpresa.getSelectedRow();
        String s = "\nNome: " + jTableListarEmpresa.getValueAt(selecionada, 0).toString()
                + "\nÁrea: " + jTableListarEmpresa.getValueAt(selecionada, 1).toString()
                + "\nSegmento: " + jTableListarEmpresa.getValueAt(selecionada, 2).toString();

        JOptionPane.showMessageDialog(null, s, "Empresa Cadastrada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jTableListarEmpresaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListarEmpresa;
    // End of variables declaration//GEN-END:variables
}
