package Mapeamento;
// Generated 18/11/2016 18:04:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private long codigoempresa;
     private String segmentomercado;
     private String nomefantasia;
     private String area;
     private Set reclamacaos = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(long codigoempresa, String segmentomercado, String nomefantasia, String area) {
        this.codigoempresa = codigoempresa;
        this.segmentomercado = segmentomercado;
        this.nomefantasia = nomefantasia;
        this.area = area;
    }
    public Empresa(long codigoempresa, String segmentomercado, String nomefantasia, String area, Set reclamacaos) {
       this.codigoempresa = codigoempresa;
       this.segmentomercado = segmentomercado;
       this.nomefantasia = nomefantasia;
       this.area = area;
       this.reclamacaos = reclamacaos;
    }
   
    public long getCodigoempresa() {
        return this.codigoempresa;
    }
    
    public void setCodigoempresa(long codigoempresa) {
        this.codigoempresa = codigoempresa;
    }
    public String getSegmentomercado() {
        return this.segmentomercado;
    }
    
    public void setSegmentomercado(String segmentomercado) {
        this.segmentomercado = segmentomercado;
    }
    public String getNomefantasia() {
        return this.nomefantasia;
    }
    
    public void setNomefantasia(String nomefantasia) {
        this.nomefantasia = nomefantasia;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Set getReclamacaos() {
        return this.reclamacaos;
    }
    
    public void setReclamacaos(Set reclamacaos) {
        this.reclamacaos = reclamacaos;
    }




}


