package Mapeamento;
// Generated 18/11/2016 18:04:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reclamacao generated by hbm2java
 */
public class Reclamacao  implements java.io.Serializable {


     private long codigoreclamacao;
     private Empresa empresa;
     private Usuario usuario;
     private String regiao;
     private String uf;
     private String cidade;
     private String assunto;
     private int mesabertura;
     private Date dataabertura;
     private Integer notaconsumidor;
     private int anoabertura;
     private String comocomproucontratou;
     private String grupoproblema;
     private char procurouempresa;
     private Integer temporesposta;
     private String avaliacaoreclamacao;
     private String situacao;
     private char respondida;
     private Date datafinalizacao;
     private Date dataresposta;
     private String problema;

    public Reclamacao() {
    }

	
    public Reclamacao(long codigoreclamacao, Empresa empresa, Usuario usuario, String regiao, String uf, String cidade, String assunto, int mesabertura, Date dataabertura, int anoabertura, String comocomproucontratou, String grupoproblema, char procurouempresa, String avaliacaoreclamacao, String situacao, char respondida, Date datafinalizacao, String problema) {
        this.codigoreclamacao = codigoreclamacao;
        this.empresa = empresa;
        this.usuario = usuario;
        this.regiao = regiao;
        this.uf = uf;
        this.cidade = cidade;
        this.assunto = assunto;
        this.mesabertura = mesabertura;
        this.dataabertura = dataabertura;
        this.anoabertura = anoabertura;
        this.comocomproucontratou = comocomproucontratou;
        this.grupoproblema = grupoproblema;
        this.procurouempresa = procurouempresa;
        this.avaliacaoreclamacao = avaliacaoreclamacao;
        this.situacao = situacao;
        this.respondida = respondida;
        this.datafinalizacao = datafinalizacao;
        this.problema = problema;
    }
    public Reclamacao(long codigoreclamacao, Empresa empresa, Usuario usuario, String regiao, String uf, String cidade, String assunto, int mesabertura, Date dataabertura, Integer notaconsumidor, int anoabertura, String comocomproucontratou, String grupoproblema, char procurouempresa, Integer temporesposta, String avaliacaoreclamacao, String situacao, char respondida, Date datafinalizacao, Date dataresposta, String problema) {
       this.codigoreclamacao = codigoreclamacao;
       this.empresa = empresa;
       this.usuario = usuario;
       this.regiao = regiao;
       this.uf = uf;
       this.cidade = cidade;
       this.assunto = assunto;
       this.mesabertura = mesabertura;
       this.dataabertura = dataabertura;
       this.notaconsumidor = notaconsumidor;
       this.anoabertura = anoabertura;
       this.comocomproucontratou = comocomproucontratou;
       this.grupoproblema = grupoproblema;
       this.procurouempresa = procurouempresa;
       this.temporesposta = temporesposta;
       this.avaliacaoreclamacao = avaliacaoreclamacao;
       this.situacao = situacao;
       this.respondida = respondida;
       this.datafinalizacao = datafinalizacao;
       this.dataresposta = dataresposta;
       this.problema = problema;
    }
   
    public long getCodigoreclamacao() {
        return this.codigoreclamacao;
    }
    
    public void setCodigoreclamacao(long codigoreclamacao) {
        this.codigoreclamacao = codigoreclamacao;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getAssunto() {
        return this.assunto;
    }
    
    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }
    public int getMesabertura() {
        return this.mesabertura;
    }
    
    public void setMesabertura(int mesabertura) {
        this.mesabertura = mesabertura;
    }
    public Date getDataabertura() {
        return this.dataabertura;
    }
    
    public void setDataabertura(Date dataabertura) {
        this.dataabertura = dataabertura;
    }
    public Integer getNotaconsumidor() {
        return this.notaconsumidor;
    }
    
    public void setNotaconsumidor(Integer notaconsumidor) {
        this.notaconsumidor = notaconsumidor;
    }
    public int getAnoabertura() {
        return this.anoabertura;
    }
    
    public void setAnoabertura(int anoabertura) {
        this.anoabertura = anoabertura;
    }
    public String getComocomproucontratou() {
        return this.comocomproucontratou;
    }
    
    public void setComocomproucontratou(String comocomproucontratou) {
        this.comocomproucontratou = comocomproucontratou;
    }
    public String getGrupoproblema() {
        return this.grupoproblema;
    }
    
    public void setGrupoproblema(String grupoproblema) {
        this.grupoproblema = grupoproblema;
    }
    public char getProcurouempresa() {
        return this.procurouempresa;
    }
    
    public void setProcurouempresa(char procurouempresa) {
        this.procurouempresa = procurouempresa;
    }
    public Integer getTemporesposta() {
        return this.temporesposta;
    }
    
    public void setTemporesposta(Integer temporesposta) {
        this.temporesposta = temporesposta;
    }
    public String getAvaliacaoreclamacao() {
        return this.avaliacaoreclamacao;
    }
    
    public void setAvaliacaoreclamacao(String avaliacaoreclamacao) {
        this.avaliacaoreclamacao = avaliacaoreclamacao;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public char getRespondida() {
        return this.respondida;
    }
    
    public void setRespondida(char respondida) {
        this.respondida = respondida;
    }
    public Date getDatafinalizacao() {
        return this.datafinalizacao;
    }
    
    public void setDatafinalizacao(Date datafinalizacao) {
        this.datafinalizacao = datafinalizacao;
    }
    public Date getDataresposta() {
        return this.dataresposta;
    }
    
    public void setDataresposta(Date dataresposta) {
        this.dataresposta = dataresposta;
    }
    public String getProblema() {
        return this.problema;
    }
    
    public void setProblema(String problema) {
        this.problema = problema;
    }




}


