package Mapeamento;
// Generated 18/11/2016 18:04:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long codigousuario;
     private String faixaetaria;
     private char sexo;
     private Set reclamacaos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long codigousuario, String faixaetaria, char sexo) {
        this.codigousuario = codigousuario;
        this.faixaetaria = faixaetaria;
        this.sexo = sexo;
    }
    public Usuario(long codigousuario, String faixaetaria, char sexo, Set reclamacaos) {
       this.codigousuario = codigousuario;
       this.faixaetaria = faixaetaria;
       this.sexo = sexo;
       this.reclamacaos = reclamacaos;
    }
   
    public long getCodigousuario() {
        return this.codigousuario;
    }
    
    public void setCodigousuario(long codigousuario) {
        this.codigousuario = codigousuario;
    }
    public String getFaixaetaria() {
        return this.faixaetaria;
    }
    
    public void setFaixaetaria(String faixaetaria) {
        this.faixaetaria = faixaetaria;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public Set getReclamacaos() {
        return this.reclamacaos;
    }
    
    public void setReclamacaos(Set reclamacaos) {
        this.reclamacaos = reclamacaos;
    }




}


