/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Relatorio;

import DAO.GeneralDAO;
import Visao.Reclamacao.ListarReclamacoes;
import java.awt.Frame;
import java.text.DecimalFormat;
import java.util.List;

/**
 *
 * @author Gustavo
 */
public class Relatorio_ReclamacaoPerCapta extends javax.swing.JDialog {

    private final GeneralDAO dao;
    private List<String> estados;
    private String estado;
    private Frame parent;

    /**
     * Creates new form Relatorio_IndiceSolucao
     *
     * @param parent
     * @param modal
     * @param dao
     */
    public Relatorio_ReclamacaoPerCapta(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        this.parent = parent;
        preencherComboBox();

        if (estado == null) {
            estado = estados.get(0);
        }

        calcularIndice();
    }

    private void preencherComboBox() {
        estados = dao.buscaAtributo("select distinct(uf) from Reclamacao order by uf");
        estados.stream().forEach((s) -> {
            jComboBoxEstado.addItem(s);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Indíce de Reclamação Per Capta do Estados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Estado");

        jComboBoxEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextAreaResultado.setRows(5);
        jTextAreaResultado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaResultado.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaResultado);

        jButton1.setText("Gráfico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        estado = jComboBoxEstado.getSelectedItem().toString();

        calcularIndice();
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GraficoPerCapta dialog = new GraficoPerCapta(parent, true, dao);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calcularIndice() {

        long quantidadeReclamacao = dao.codigo("select count(codigoreclamacao)"
                + " from Reclamacao where uf='" + estado + "'");

        int populacao = 0;
        switch (estado) {
            case "SP":
                populacao = 44396484;
                break;
            case "MG":
                populacao = 20869101;
                break;
            case "RJ":
                populacao = 16550024;
                break;
            case "BA":
                populacao = 15203934;
                break;
            case "RS":
                populacao = 11247972;
                break;
            case "PR":
                populacao = 11163018;
                break;
            case "PE":
                populacao = 9345173;
                break;
            case "CE":
                populacao = 8904459;
                break;
            case "PA":
                populacao = 8175113;
                break;
            case "MA":
                populacao = 6904241;
                break;
            case "SC":
                populacao = 6819190;
                break;
            case "GO":
                populacao = 6610681;
                break;
            case "PB":
                populacao = 3972202;
                break;
            case "AM":
                populacao = 3938336;
                break;
            case "ES":
                populacao = 3929911;
                break;
            case "RN":
                populacao = 3442175;
                break;
            case "AL":
                populacao = 3340932;
                break;
            case "MT":
                populacao = 3270973;
                break;
            case "PI":
                populacao = 3204028;
                break;
            case "DF":
                populacao = 2914830;
                break;
            case "MS":
                populacao = 2651235;
                break;
            case "SE":
                populacao = 2242937;
                break;
            case "RO":
                populacao = 1768204;
                break;
            case "TO":
                populacao = 1515126;
                break;
            case "AC":
                populacao = 803513;
                break;
            case "AP":
                populacao = 803513;
                break;
            case "RR":
                populacao = 505665;
                break;
        }

        double porestado = (double) ((double) (quantidadeReclamacao) / (double) (populacao));
        DecimalFormat format = new DecimalFormat("#.#######");
        jTextAreaResultado.setText("Indíce de Reclamação Per Capta de "
                + estado + ": " + format.format(porestado));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultado;
    // End of variables declaration//GEN-END:variables
}
