/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Relatorio;

import Controle.ControleEmpresa;
import Controle.ControlePrincipal;
import DAO.DAO_Relatorio;
import DAO.GeneralDAO;
import Modelo.ModeloTabela;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Gustavo
 */
public class Relatorio_Empresa extends javax.swing.JDialog {

    private GeneralDAO dao;
    private ControlePrincipal controlePrincipal = new ControlePrincipal();

    /**
     * Creates new form Relatorio_Empresa
     */
    public Relatorio_Empresa(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        jLabelCidade.setVisible(false);
        jTextFieldCidade.setVisible(false);
        jLabelQtd.setVisible(false);
        jTextFieldQtd.setVisible(false);
        jLabelTempoMedio.setVisible(false);
        jTextFieldTempoMedio.setVisible(false);
        Toolkit kit = this.getToolkit();
        Image icone = kit.getImage("src/Icones/relatorio.png");
        this.setIconImage(icone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeEmpresa = new javax.swing.JTextField();
        jButtonBuscarReclamacao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresasBuscadasBuscar = new javax.swing.JTable();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelQtd = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabelTempoMedio = new javax.swing.JLabel();
        jTextFieldTempoMedio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório por Empresa");

        jLabel1.setText("Nome:");

        jButtonBuscarReclamacao.setText("Buscar");
        jButtonBuscarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarReclamacaoActionPerformed(evt);
            }
        });

        jTableEmpresasBuscadasBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEmpresasBuscadasBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpresasBuscadasBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpresasBuscadasBuscar);

        jLabelCidade.setText("Cidade mais reclamada:");

        jTextFieldCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCidade.setEnabled(false);

        jLabelQtd.setText("Quantidade de Reclamações: ");

        jTextFieldQtd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQtd.setEnabled(false);

        jLabelTempoMedio.setText("Tempo Médio de Resposta:");

        jTextFieldTempoMedio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTempoMedio.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNomeEmpresa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jButtonBuscarReclamacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(292, 292, 292))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelQtd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTempoMedio)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTempoMedio)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldCidade, jTextFieldQtd, jTextFieldTempoMedio});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarReclamacao)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQtd))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempoMedio)
                    .addComponent(jTextFieldTempoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarReclamacaoActionPerformed
        String nome = jTextFieldNomeEmpresa.getText();
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome de busca!", "Campo Vazio", JOptionPane.ERROR_MESSAGE);

        } else {

            ArrayList empresas = controlePrincipal.buscarEmpresa(nome, dao);
            if (empresas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Empresa " + nome + " não encontrada!", "Empresa não encontrada", JOptionPane.INFORMATION_MESSAGE);
            } else {
                jTextFieldCidade.setText("");
                jTextFieldQtd.setText("");
                preencherTabela(empresas, nome);
            }
        }
    }//GEN-LAST:event_jButtonBuscarReclamacaoActionPerformed

    private void jTableEmpresasBuscadasBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpresasBuscadasBuscarMouseClicked
        int selecionada = jTableEmpresasBuscadasBuscar.getSelectedRow();

        String nome = jTableEmpresasBuscadasBuscar.getValueAt(selecionada, 0).toString();
        String area = jTableEmpresasBuscadasBuscar.getValueAt(selecionada, 1).toString();
        String segmento = jTableEmpresasBuscadasBuscar.getValueAt(selecionada, 2).toString();

        ControleEmpresa controleEmpresa = new ControleEmpresa();
        long codigoEmpresa = controleEmpresa.buscaCodigoEmpresaCompleto(nome, area, segmento, dao);
        DAO_Relatorio dao_relatorio = new DAO_Relatorio(dao.getSessao());

        jTextFieldCidade.setText("");
        jTextFieldQtd.setText("");

        quantidade(codigoEmpresa);
        cidade(codigoEmpresa, dao_relatorio);

    }//GEN-LAST:event_jTableEmpresasBuscadasBuscarMouseClicked

    private void quantidade(long codigoEmpresa) {
        jLabelQtd.setVisible(true);
        jTextFieldQtd.setVisible(true);

        String consulta = "select count(codigoreclamacao) from Reclamacao"
                + " where codempresa = " + codigoEmpresa;

        jTextFieldQtd.setText(String.valueOf(dao.codigo(consulta)));

    }

    private void cidade(long codigoEmpresa, DAO_Relatorio dao_relatorio) {
        String consulta
                = "select cidade"
                + " from Reclamacao where codempresa =" + codigoEmpresa + "group by cidade"
                + " order by count(codigoreclamacao) desc";

        String cidade = dao_relatorio.cidadeMaisReclamada(consulta);

        jLabelCidade.setVisible(true);
        jTextFieldCidade.setVisible(true);
        jTextFieldCidade.setText(cidade);
    }

    private void preencherTabela(ArrayList empresas, String nome) {
        try {
            String[] nomeColunas = new String[]{"Nome", "Área", "Segmento Mercado"};

            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            ModeloTabela modeloTabela = new ModeloTabela(empresas, nomeColunas);
            jTableEmpresasBuscadasBuscar.setModel(modeloTabela);

            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(0).setResizable(true);
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(0).setHeaderValue(modeloTabela.getColumnNome(0));
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(0).setCellRenderer(centralizado);

            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(1).setResizable(true);
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(1).setHeaderValue(modeloTabela.getColumnNome(1));
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(1).setCellRenderer(centralizado);

            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(2).setResizable(true);
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(2).setHeaderValue(modeloTabela.getColumnNome(2));
            jTableEmpresasBuscadasBuscar.getColumnModel().getColumn(2).setCellRenderer(centralizado);

            jTableEmpresasBuscadasBuscar.getTableHeader().setReorderingAllowed(false);
            jTableEmpresasBuscadasBuscar.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTableEmpresasBuscadasBuscar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "Erro ao listar as empresas de nome " + nome + "!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarReclamacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JLabel jLabelTempoMedio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresasBuscadasBuscar;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldNomeEmpresa;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldTempoMedio;
    // End of variables declaration//GEN-END:variables
}
