/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Reclamacao;

import Controle.ControlePrincipal;
import Modelo.ModeloTabela;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import DAO.GeneralDAO;
import java.util.Date;

/**
 *
 * @author Gustavo
 */
public class CadastrarReclamacao extends javax.swing.JDialog {

    private GeneralDAO dao;
    private ControlePrincipal controlePrincipal = new ControlePrincipal();

    private String assunto, comocomproucontratou, grupoproblema, avaliacaoreclamacao;
    private String situacao, respondida, problema;
    private String procurouempresa, regiao, cidade, uf;
    private int mesabertura, nota = -1, anoabertura, temporesposta;
    private Date dataabertura, dataresposta, datafinalizacao;
    private String sexo, faixaetaria;
    private String nomefantasia, area, segmentomercado;
    private boolean usuario = false;
    private boolean empresa = false;
    private List<String> assuntos, comocomproucont, grupoproblem, problem, city;

    /**
     * Creates new form CadastrarReclamacao
     */
    public CadastrarReclamacao(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        preencherComboBoxs();
        preencherTabelaUsuario();
        preencherTabelaEmpresa();
        jTextFieldUsuario.setEditable(false);
        jTextFieldEmpresa.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxAssunto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMesAbertura = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton0 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButtonCadastrarReclamacao = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxAnoAbertura = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxComoComprouContratou = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxGrupoProblema = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxProcurouEmpresa = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTempoResposta = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxAvaliacaoReclamacao = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxRespondida = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxProblema = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jScrollPaneUsuario = new javax.swing.JScrollPane();
        jTableListarUsuario = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jScrollPaneUsuario1 = new javax.swing.JScrollPane();
        jTableListarEmpresa = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jDateChooserAbertura = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserResposta = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jDateChooserFinalizacao = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxRegiao = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxUF = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Reclamação");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Assunto");

        jComboBoxAssunto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAssuntoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mês Abertura");

        jComboBoxMesAbertura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxMesAbertura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "9", "10", "11", "12" }));
        jComboBoxMesAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesAberturaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nota Consumidor");

        jRadioButton0.setText("0");
        jRadioButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton0ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jButtonCadastrarReclamacao.setText("Cadastrar Reclamação");
        jButtonCadastrarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarReclamacaoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ano Abertura");

        jComboBoxAnoAbertura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxAnoAbertura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016" }));
        jComboBoxAnoAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoAberturaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Como Comprou e Contratou");

        jComboBoxComoComprouContratou.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxComoComprouContratou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComoComprouContratouActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Grupo Problema");

        jComboBoxGrupoProblema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxGrupoProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrupoProblemaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Procurou Empresa");

        jComboBoxProcurouEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxProcurouEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        jComboBoxProcurouEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProcurouEmpresaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tempo Resposta");

        jComboBoxTempoResposta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxTempoResposta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxTempoResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTempoRespostaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Avaliação Reclamação");

        jComboBoxAvaliacaoReclamacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxAvaliacaoReclamacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Resolvida", "Não resolvida", "Não Avaliada" }));
        jComboBoxAvaliacaoReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAvaliacaoReclamacaoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Situação");

        jComboBoxSituacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Finalizada avaliada", "Finalizada não avaliada", "Respondida" }));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Respondida");

        jComboBoxRespondida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxRespondida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        jComboBoxRespondida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRespondidaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Problema");

        jComboBoxProblema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProblemaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Usuário");

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jTableListarUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarUsuarioMouseClicked(evt);
            }
        });
        jScrollPaneUsuario.setViewportView(jTableListarUsuario);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Empresa");

        jTextFieldEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpresaActionPerformed(evt);
            }
        });

        jTableListarEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarEmpresaMouseClicked(evt);
            }
        });
        jScrollPaneUsuario1.setViewportView(jTableListarEmpresa);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Data Abertura");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Data Resposta");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Data Finalização");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Região");

        jComboBoxRegiao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxRegiao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CO", "N", "NE", "S", "SE" }));
        jComboBoxRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRegiaoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("UF");

        jComboBoxUF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        jComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Cidade");

        jComboBoxCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jComboBoxAssunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(750, 750, 750)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTempoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRespondida, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxAvaliacaoReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMesAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAnoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxGrupoProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(jComboBoxProcurouEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(241, 241, 241)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jComboBoxRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(jButtonCadastrarReclamacao)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxComoComprouContratou, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPaneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmpresa)
                                    .addComponent(jScrollPaneUsuario1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(574, 574, 574)
                                .addComponent(jComboBoxProblema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxMesAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooserFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jDateChooserResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxAnoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxProcurouEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxGrupoProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton0))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxAvaliacaoReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxTempoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxRespondida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel20)
                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxComoComprouContratou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jButtonCadastrarReclamacao)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAssuntoActionPerformed
        assunto = jComboBoxAssunto.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxAssuntoActionPerformed

    private void jComboBoxMesAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesAberturaActionPerformed
        mesabertura = Integer.parseInt(jComboBoxMesAbertura.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxMesAberturaActionPerformed

    private void jRadioButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton0ActionPerformed
        nota = 0;
    }//GEN-LAST:event_jRadioButton0ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        nota = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonCadastrarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarReclamacaoActionPerformed

        if (anoabertura == 0) {
            anoabertura = 2014;
        }
        if (assunto == null) {
            assunto = assuntos.get(0);
        }
        if (avaliacaoreclamacao == null) {
            avaliacaoreclamacao = "Resolvida";
        }
        if (comocomproucontratou == null) {
            comocomproucontratou = comocomproucont.get(0);
        }
        if (grupoproblema == null) {
            grupoproblema = grupoproblem.get(0);
        }
        if (mesabertura == 0) {
            mesabertura = 1;
        }
        if (problema == null) {
            problema = problem.get(0);
        }
        if (procurouempresa == null) {
            procurouempresa = "Sim";
        }
        if (respondida == null) {
            respondida = "Sim";
        }
        if (situacao == null) {
            situacao = "Finalizada avaliada";
        }

        if (regiao == null) {
            regiao = "CO";
        }

        if (uf == null) {
            uf = "AC";
        }

        if (cidade == null) {
            cidade = city.get(0);
        }
        if (jComboBoxTempoResposta.getSelectedItem().toString() == null) {
            temporesposta = 0;
        }

        if (this.jDateChooserAbertura.getDate() != null) {
            dataabertura = this.jDateChooserAbertura.getDate();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma data de abertura!", "Data Abertura", JOptionPane.WARNING_MESSAGE);
        }

        if (this.jDateChooserResposta.getDate() != null) {
            dataresposta = this.jDateChooserResposta.getDate();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma data de resposta!", "Data Resposta", JOptionPane.WARNING_MESSAGE);
        }

        if (this.jDateChooserFinalizacao.getDate() != null) {
            datafinalizacao = this.jDateChooserFinalizacao.getDate();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma data de finalização!", "Data Finalização", JOptionPane.WARNING_MESSAGE);
        }

        if (nota == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma nota para a reclamação!", "Nota Consumidor", JOptionPane.WARNING_MESSAGE);
        } else if (!usuario && empresa) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário!", "Informação", JOptionPane.WARNING_MESSAGE);
        } else if (!empresa && usuario) {
            JOptionPane.showMessageDialog(null, "Selecione uma empresa!", "Informação", JOptionPane.WARNING_MESSAGE);
        } else if (!empresa && !usuario) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário e uma empresa!", "Informação", JOptionPane.WARNING_MESSAGE);
        } else {
            java.sql.Date dataAberturaSQL = new java.sql.Date(dataabertura.getTime());
            java.sql.Date dataRespostaSQL = new java.sql.Date(dataresposta.getTime());
            java.sql.Date dataFinalizacaoSQL = new java.sql.Date(datafinalizacao.getTime());

            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String s
                    = "Reclamação a ser inserida:"
                    + "\n\nRegião: " + regiao
                    + "\nUF: " + uf
                    + "\nCidade: " + cidade
                    + "\n\nAssunto: " + assunto
                    + "\nMes Abertura: " + mesabertura
                    + "\nAno abertura: " + anoabertura
                    + "\nData Abertura: " + simpleDateFormat.format(dataabertura)
                    + "\nNota Consumidor: " + nota
                    + "\nComo Comprou Contratou: " + comocomproucontratou
                    + "\nGrupo Problema: " + grupoproblema
                    + "\nProcurou Emprea: " + procurouempresa
                    + "\nTempo Resposta: " + temporesposta
                    + "\nAvaliação Reclamação: " + avaliacaoreclamacao
                    + "\nSituação: " + situacao
                    + "\nRespondida: " + respondida
                    + "\nData Finalização: " + simpleDateFormat.format(datafinalizacao)
                    + "\nData Resposta: " + simpleDateFormat.format(dataresposta)
                    + "\nProblema: " + problema
                    + "\n\nSexo Usuário: " + sexo
                    + "\nFaixa Etária Usuário: " + faixaetaria
                    + "\n\nNome Empresa: " + nomefantasia
                    + "\nÁrea: " + area
                    + "\nSegmento Mercado: " + segmentomercado
                    + "\n\nDeseja inserir esta reclamação?";

            int opcao = JOptionPane.showConfirmDialog(null, s, "Inserir Reclamação", JOptionPane.YES_NO_OPTION);

            if (opcao == JOptionPane.YES_OPTION) {
                if (controlePrincipal.cadastrarReclamacao(regiao, uf, cidade, assunto, mesabertura,
                        dataAberturaSQL,
                        nota, anoabertura, comocomproucontratou, grupoproblema, procurouempresa,
                        temporesposta, avaliacaoreclamacao, situacao, respondida, dataFinalizacaoSQL,
                        dataRespostaSQL, problema, dao, nomefantasia, area, segmentomercado, sexo,
                        faixaetaria)) {

                    JOptionPane.showMessageDialog(null, "Reclamação cadastrada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Reclamação não foi cadastrada!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_jButtonCadastrarReclamacaoActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        nota = 2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        nota = 3;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        nota = 4;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        nota = 5;
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jComboBoxAnoAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoAberturaActionPerformed
        anoabertura = Integer.parseInt(jComboBoxAnoAbertura.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxAnoAberturaActionPerformed

    private void jComboBoxComoComprouContratouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComoComprouContratouActionPerformed
        comocomproucontratou = jComboBoxComoComprouContratou.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxComoComprouContratouActionPerformed

    private void jComboBoxGrupoProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrupoProblemaActionPerformed
        grupoproblema = jComboBoxGrupoProblema.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxGrupoProblemaActionPerformed

    private void jComboBoxProcurouEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProcurouEmpresaActionPerformed
        procurouempresa = jComboBoxProcurouEmpresa.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxProcurouEmpresaActionPerformed

    private void jComboBoxTempoRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTempoRespostaActionPerformed
        temporesposta = Integer.parseInt(jComboBoxTempoResposta.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxTempoRespostaActionPerformed

    private void jComboBoxAvaliacaoReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAvaliacaoReclamacaoActionPerformed
        avaliacaoreclamacao = jComboBoxAvaliacaoReclamacao.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxAvaliacaoReclamacaoActionPerformed

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        situacao = jComboBoxSituacao.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    private void jComboBoxRespondidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRespondidaActionPerformed
        respondida = jComboBoxRespondida.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxRespondidaActionPerformed

    private void jComboBoxProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProblemaActionPerformed
        problema = jComboBoxProblema.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxProblemaActionPerformed

    public void preencherTabelaUsuario() {

        try {
            String[] nomeColunas = new String[]{"Sexo", "Faixa Etária"};
            ArrayList dados = controlePrincipal.listarUsuarios(dao);
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            ModeloTabela modeloTabela = new ModeloTabela(dados, nomeColunas);
            jTableListarUsuario.setModel(modeloTabela);

            jTableListarUsuario.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableListarUsuario.getColumnModel().getColumn(0).setResizable(true);
            jTableListarUsuario.getColumnModel().getColumn(0).setHeaderValue(modeloTabela.getColumnNome(0));
            jTableListarUsuario.getColumnModel().getColumn(0).setCellRenderer(centralizado);

            jTableListarUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableListarUsuario.getColumnModel().getColumn(1).setResizable(true);
            jTableListarUsuario.getColumnModel().getColumn(1).setHeaderValue(modeloTabela.getColumnNome(1));
            jTableListarUsuario.getColumnModel().getColumn(1).setCellRenderer(centralizado);

            jTableListarUsuario.getTableHeader().setReorderingAllowed(false);
            jTableListarUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTableListarUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os usuários cadastrados!");
        }
    }

    public void preencherTabelaEmpresa() {

        try {
            String[] nomeColunas = new String[]{"Nome", "Área", "Segmento Mercado"};
            ArrayList dados = controlePrincipal.listarEmpresas(dao);
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            ModeloTabela modeloTabela = new ModeloTabela(dados, nomeColunas);
            jTableListarEmpresa.setModel(modeloTabela);

            jTableListarEmpresa.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableListarEmpresa.getColumnModel().getColumn(0).setResizable(true);
            jTableListarEmpresa.getColumnModel().getColumn(0).setHeaderValue(modeloTabela.getColumnNome(0));
            jTableListarEmpresa.getColumnModel().getColumn(0).setCellRenderer(centralizado);

            jTableListarEmpresa.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableListarEmpresa.getColumnModel().getColumn(1).setResizable(true);
            jTableListarEmpresa.getColumnModel().getColumn(1).setHeaderValue(modeloTabela.getColumnNome(1));
            jTableListarEmpresa.getColumnModel().getColumn(1).setCellRenderer(centralizado);

            jTableListarEmpresa.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableListarEmpresa.getColumnModel().getColumn(2).setResizable(true);
            jTableListarEmpresa.getColumnModel().getColumn(2).setHeaderValue(modeloTabela.getColumnNome(2));
            jTableListarEmpresa.getColumnModel().getColumn(2).setCellRenderer(centralizado);

            jTableListarEmpresa.getTableHeader().setReorderingAllowed(false);
            jTableListarEmpresa.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTableListarEmpresa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "Erro ao listar as empresas cadastradas!");
        }
    }

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jTableListarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarUsuarioMouseClicked
        usuario = true;
        int selecionada = jTableListarUsuario.getSelectedRow();

        sexo = jTableListarUsuario.getValueAt(selecionada, 0).toString();
        faixaetaria = jTableListarUsuario.getValueAt(selecionada, 1).toString();

        jTextFieldUsuario.setText(sexo + ",   " + faixaetaria);
    }//GEN-LAST:event_jTableListarUsuarioMouseClicked

    private void jTextFieldEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpresaActionPerformed

    private void jTableListarEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarEmpresaMouseClicked
        empresa = true;
        int selecionada = jTableListarEmpresa.getSelectedRow();

        nomefantasia = jTableListarEmpresa.getValueAt(selecionada, 0).toString();
        area = jTableListarEmpresa.getValueAt(selecionada, 1).toString();
        segmentomercado = jTableListarEmpresa.getValueAt(selecionada, 2).toString();

        jTextFieldEmpresa.setText(nomefantasia + ",   " + area + ",   " + segmentomercado);
    }//GEN-LAST:event_jTableListarEmpresaMouseClicked

    private void jComboBoxRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRegiaoActionPerformed
        regiao = jComboBoxRegiao.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxRegiaoActionPerformed

    private void jComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFActionPerformed
        uf = jComboBoxUF.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxUFActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        cidade = jComboBoxCidade.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void preencherComboBoxs() {

        assuntos = controlePrincipal.assuntos(dao);
        for (String s : assuntos) {
            jComboBoxAssunto.addItem(s + "\n");
        }

        comocomproucont = controlePrincipal.comoComprouContratou(dao);
        for (String s : comocomproucont) {
            jComboBoxComoComprouContratou.addItem(s + "\n");
        }

        grupoproblem = controlePrincipal.grupoProblema(dao);
        for (String s : grupoproblem) {
            jComboBoxGrupoProblema.addItem(s + "\n");
        }

        problem = controlePrincipal.problema(dao);
        for (String s : problem) {
            jComboBoxProblema.addItem(s + "\n");
        }

        city = controlePrincipal.cidade(dao);
        for (String s : city) {
            jComboBoxCidade.addItem(s + "\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarReclamacao;
    private javax.swing.JComboBox jComboBoxAnoAbertura;
    private javax.swing.JComboBox jComboBoxAssunto;
    private javax.swing.JComboBox jComboBoxAvaliacaoReclamacao;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxComoComprouContratou;
    private javax.swing.JComboBox jComboBoxGrupoProblema;
    private javax.swing.JComboBox jComboBoxMesAbertura;
    private javax.swing.JComboBox jComboBoxProblema;
    private javax.swing.JComboBox jComboBoxProcurouEmpresa;
    private javax.swing.JComboBox jComboBoxRegiao;
    private javax.swing.JComboBox jComboBoxRespondida;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JComboBox jComboBoxTempoResposta;
    private javax.swing.JComboBox jComboBoxUF;
    private com.toedter.calendar.JDateChooser jDateChooserAbertura;
    private com.toedter.calendar.JDateChooser jDateChooserFinalizacao;
    private com.toedter.calendar.JDateChooser jDateChooserResposta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton0;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPaneUsuario;
    private javax.swing.JScrollPane jScrollPaneUsuario1;
    private javax.swing.JTable jTableListarEmpresa;
    private javax.swing.JTable jTableListarUsuario;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
