/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Usuario;

import Controle.ControlePrincipal;
import Controle.*;
import Mapeamento.Usuario;
import Modelo.ModeloTabela;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import DAO.GeneralDAO;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Gustavo
 */
public class ListarUsuario extends javax.swing.JDialog {

    private GeneralDAO dao;
    private ControlePrincipal controlePrincipal = new ControlePrincipal();

    /**
     * Creates new form ListarUsuario
     */
    public ListarUsuario(java.awt.Frame parent, boolean modal, GeneralDAO dao) {
        super(parent, modal);
        initComponents();
        this.dao = dao;
        preencherTabela();

        Toolkit kit = this.getToolkit();
        Image icone = kit.getImage("src/Icones/usuario.png");
        this.setIconImage(icone);
        
        jTableListarUsuario.setAutoCreateRowSorter(true);
    }

    public void preencherTabela() {

        try {
            String[] nomeColunas = new String[]{"Sexo", "Faixa Etária"};
            ArrayList dados = controlePrincipal.listarUsuarios(dao);
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            ModeloTabela modeloTabela = new ModeloTabela(dados, nomeColunas);
            jTableListarUsuario.setModel(modeloTabela);

            jTableListarUsuario.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableListarUsuario.getColumnModel().getColumn(0).setResizable(true);
            jTableListarUsuario.getColumnModel().getColumn(0).setHeaderValue(modeloTabela.getColumnNome(0));
            jTableListarUsuario.getColumnModel().getColumn(0).setCellRenderer(centralizado);

            jTableListarUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableListarUsuario.getColumnModel().getColumn(1).setResizable(true);
            jTableListarUsuario.getColumnModel().getColumn(1).setHeaderValue(modeloTabela.getColumnNome(1));
            jTableListarUsuario.getColumnModel().getColumn(1).setCellRenderer(centralizado);

            jTableListarUsuario.getTableHeader().setReorderingAllowed(false);
            jTableListarUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTableListarUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os usuários cadastrados!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarUsuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários Cadastrados");

        jTableListarUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableListarUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListarUsuario;
    // End of variables declaration//GEN-END:variables
}
